### ISSUE TITLE
By default, the getent command does not exist.

### ISSUE THREAD

**Issue by fxzxmic** [jirutka/doas-sudo-shim#6]
https://github.com/jirutka/doas-sudo-shim/blob/0cf9c9b4c5c7b5a5b517f569fc9cc16ebfb08253/sudo#L59C29-L59C29
So can other commands be used instead?

**Comment by jirutka** [comment]
Where it doesn't exist, what distro do you use?

**Comment by fxzxmic** [comment]
The getent command is a part of musl-utils package on Alpine Linux.

**Comment by jirutka** [comment]
Yes and musl-utils is a dependency of [alpine-base](https://pkgs.alpinelinux.org/packages?name=alpine-base). However, you’re right that it’s not declared as a dependency of the `doas-sudo-shim` aport, and it should be. About other distros, as I know, `getenv` comes by default with glibc.

That said, I didn’t realise that; I’ll consider replacing it with simple _sed_ to avoid extra dependency.

**Comment by fxzxmic** [comment]
OK, thanks.
