### ISSUE TITLE
sudo bash script permit input scrips?

### ISSUE THREAD

**Issue by mckaygerhard** [jirutka/doas-sudo-shim#7]
i can see that arguments on sudo script allows any input inside arguments.. this can leak some kind of security risk i guess

**Comment by jirutka** [comment]
I can’t imagine how this could be a secuiry threat. Can you be more specific?

**Comment by mckaygerhard** [comment]
well the `<user>` argument its a free input.. its allow any king of input.. so?  same for `<command> [--] [<args>...]`

**Comment by jirutka** [comment]
This doesn’t make sense; it looks to me as a misunderstanding of shell scripts.

**Comment by mckaygerhard** [comment]
hi @jirutka seems you miscundeerstand.. i means if the scrip allows any input and just bypass to the orignal doas.. 

if you alreayd said that about miscunderstanding of bash why you dont just posted the first time?

i already tested that script allows any kind of input and just bypas to orignal doas.. something with rare inputs of strings just breaks..
